# Generated by Django 4.2.7 on 2023-11-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedface',
            name='name',
            field=models.CharField(default='DefaultName', max_length=255),
            preserve_default=False,
        ),
    ]
